### ISSUE TITLE
CreateTextNode有什么用

### ISSUE THREAD

**Issue by dumplings** [sapling-team/team-building#1]
5月31日文文分享的早读（http://liujiacai.net/blog/2016/05/28/scope-closure/?hmsr=toutiao.io&utm_medium=toutiao.io&utm_source=toutiao.io&from=groupmessage&isappinstalled=0）中，在JavaScript 中的变量作用域中首个例子有个图，用到了原生的createTextNode方法，我查了一下w3c的解释，就是去创建一个节点中的文本，不知道还有啥更深层的意思，和直接写文本有啥区别啊。

**Comment by yuanxj1024** [comment]
@Chandler0415 当使用`createTextNode`会创建一个text类型节点，跟直接写文本的区别在于此时只是个虚拟dom，必须使用appendChild，insertBefore等方法插入具体的dom后该文本节点才会显示； 

直接写文本就直接立刻响应到对应的dom上了
